apiVersion: apps/v1
kind: Deployment
metadata:
  name: drools-demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drools-demo
  template:
    metadata:
      labels:
        app: drools-demo
    spec:
      containers:
        - name: drools-demo
          image: dipu035/drools-demo:0.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: drools-demo
spec:
  selector:
    app: drools-demo
  ports:
    - protocol: TCP
      port: 8787
      targetPort: 8080
      name: grpc
  type: LoadBalancer
